# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DEC12attemptSwift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DEC12attemptSwift
pod 'SpatialDBKit', :path => './'
end
